// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOx1kgYY7mJ2OEOcmEIHvGs5K-ivIXBQU',
    appId: '1:169490531204:web:20a046379a2f3b998993d1',
    messagingSenderId: '169490531204',
    projectId: 'flutterauth-cad1b',
    authDomain: 'flutterauth-cad1b.firebaseapp.com',
    storageBucket: 'flutterauth-cad1b.firebasestorage.app',
    measurementId: 'G-RKN8YJJ4DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy6yvkj8ibnpvYzUZhglel3COWd-HJJnc',
    appId: '1:169490531204:android:28152c068b1d8ff58993d1',
    messagingSenderId: '169490531204',
    projectId: 'flutterauth-cad1b',
    storageBucket: 'flutterauth-cad1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtkGNOzVCelGhnZGsFbprVpeX_AeZwrXQ',
    appId: '1:169490531204:ios:6eaae8c97ec79ce48993d1',
    messagingSenderId: '169490531204',
    projectId: 'flutterauth-cad1b',
    storageBucket: 'flutterauth-cad1b.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtkGNOzVCelGhnZGsFbprVpeX_AeZwrXQ',
    appId: '1:169490531204:ios:6eaae8c97ec79ce48993d1',
    messagingSenderId: '169490531204',
    projectId: 'flutterauth-cad1b',
    storageBucket: 'flutterauth-cad1b.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOx1kgYY7mJ2OEOcmEIHvGs5K-ivIXBQU',
    appId: '1:169490531204:web:1fe3d1c18b92c6e18993d1',
    messagingSenderId: '169490531204',
    projectId: 'flutterauth-cad1b',
    authDomain: 'flutterauth-cad1b.firebaseapp.com',
    storageBucket: 'flutterauth-cad1b.firebasestorage.app',
    measurementId: 'G-7DPRFYHW28',
  );

}